### ISSUE TITLE
Problem when trying to  run individual modules

### ISSUE THREAD

**Issue by longthanhta** [connorcoley/ASKCOS#1]
When I try to run the individual modules inside the folder 'makeit", for example:
`python tree_builder.py`
I got this error:
`"ModuleNotFoundError: No module named makeit`
Please help me solve this problem, thank you!

**Comment by connorcoley** [comment]
Part of the deployment with Docker adds the parent folder of “makeit” to
the path environment variable. I’d highly recommend setting it up with the
provided instructions since it’ll take care of all of the dependencies and
environment variables.

**Comment by tanguyenthanhlong** [comment]
Thank you for your advice,
I have install docker and after I type this command
`sudo docker-compose up -d`
I go to the folder contain tree_builder.py and run:
`python tree_builder.py`
But I still got the same error, can you suggest me some command to run the python file, for example, the file in this path:makeit/retrosynthetic/mcts/tree_builder.py
P/s: I am new to docker and my background is chemistry so I dont know much about this, but I found out that this package is amazing and I really want to use this.

**Comment by longthanhta** [comment]
Thank you for your advice, 
Finally, I could run it using this command after the deployment of Docker:
```
docker-compose exec app bash -c "python /usr/local/ASKCOS/makeit/retr
osynthetic/mcts/tree_builder.py"
```
But when I run this tree_builder.py, I got this error
Traceback (most recent call last):
Process Process-4:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
    kind, result = conn.recv()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
IOError: [Errno 104] Connection reset by peer
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/ASKCOS/makeit/retrosynthetic/mcts/tree_builder.py", line 484, in work
    self.idle[i] = True
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/ASKCOS/makeit/retrosynthetic/mcts/tree_builder.py", line 460, in work
    if self.done.value:
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 1039, in get
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    return self._callmethod('get')
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer

Please help me with this error.

One more thing, as I saw in here, this code also has a web interface, but I don't know much about docker, could you suggest some command to get this web interface running? ( I have experienced the web interface in ASKCOS website, but I want to understand more about your code)

P/s: this "IOError: [Errno 104] Connection reset by peer" sometimes appear on the web version in http://askcos.mit.edu/ as well.

**Comment by connorcoley** [comment]
Sorry for the slow response -- that error is a bug with Celery that [has not been resolved](https://github.com/celery/celery/issues/4867). We haven't identified a workaround; instead, we usually will just resubmit the tree builder job and it generally works on the 2nd try (or 3rd, or 4th...). Not ideal, I know.

As for the web interface, if you deploy using docker and docker-compose, there will be a uWSGI+Django+NGINX webserver running on port 80. If you deploy on a cloud instance, simply go to the external IP in a browser. Otherwise, go to localhost.

**Comment by longthanhta** [comment]
Thank you so much!
