### ISSUE TITLE
what's meaning of 'efgs' key in the  self.templates?

### ISSUE THREAD

**Issue by autodataming** [connorcoley/ASKCOS#21]
I can guess the meaning of these field "count rxn_example name reference intra_only incompatible_groups references intra_only incompatible_groups ..." in the info of  template. 
I can't guess the meaning of the filed "efgs".
what's meaning of 'efgs' key in the  self.templates?

**Comment by connorcoley** [comment]
efgs is a now-defunct field from an early attempt to use Extended Functional Groups (https://www.mdpi.com/1420-3049/21/1/1/htm) to provide a MACCS-like fingerprint of substrate scope compatibility for each template.

**Comment by autodataming** [comment]
> 
> 
> efgs is a now-defunct field from an early attempt to use Extended Functional Groups (https://www.mdpi.com/1420-3049/21/1/1/htm) to provide a MACCS-like fingerprint of substrate scope compatibility for each template.

Thank you.
