### ISSUE TITLE
what's the different meaning between the argument max_branching & template_count  in arg_parser.py?

### ISSUE THREAD

**Issue by tingweidaniel** [connorcoley/ASKCOS#27]
I have look through the most of script in ASKCOS; however, I still cannot figure out the clear meaning of  **max_branching** & **template_count**.  

For a simple example, if I set the **max_branching=2**, **template_count=100**, depth=1 and start from the **root A** to make a tree, I expect that I can probably get the **two child nodes, named B, C here**, of A at expansion step (due to the branching factor is 2). But where does the argument **template_count** be used in? Is the **max_branching** just a more restricted argument than **template_count**, but both of than in the same meaning?

The comment of **template_count** says: 'Maximum number of templates to be applied for each expansion step'.  I have thought that root A applied **template_count=100** to generate child nodes B & C when doing expansion. However, my thought seems a wrong concept because root A doing the same action two times...

Thank you for your help.

**Comment by connorcoley** [comment]
The `template_count` argument controls the maximum number of templates used
to generate precursors. These precursors are then scored (e.g., by the
heuristic+relevance score) and optionally filtered (by the fast filter) to
come up with a ranked list of the "best" reactant sets. Then, the top
`max_branching` sets are added to the search tree.

A few relevant considerations: (1) Not all templates we apply will
generate reactants; (2) Sometimes, multiple templates will generate the
same reactants; (3) The precursor ranks are, by default, a function of
_both_ the template relevance score and a heuristic score related to
synthetic complexity, so the top 20 precursors may not come from the top 20
templates, even if each template generates a unique precursor. For all
these reasons, we usually keep template_count >> max_branching.

**Comment by tingweidaniel** [comment]
It's a very clear explanation! I really appreciate your help in resolving my problem.
