### ISSUE TITLE
Does the rollout policy in "/makeit/retrosynthetic/mcts/tree_builder.py" use the neuron network?

### ISSUE THREAD

**Issue by tingweidaniel** [connorcoley/ASKCOS#28]
According to [Marwin Segler's work](https://www.nature.com/articles/nature25978) description, they use one hidden layer NN to randomly sampling the templates for estimating the position value during the rollout phase and use another NN in expansion step to guide the search in a promising direction.

I'm wondering whether in "/makeit/retrosynthetic/mcts/tree_builder.py" uses the same idea that applies the respective NN in expansion and rollout step or not.  I can just find the trained model's weight & bias in "ASKCOS/makeit/data/prioritization/" for expansion step, but not any for rollout step in "ASKCOS/makeit/data/*".  The rollout step in ASKCOS seems directly to use the applied result (**top_probs, top_indeces**) from template relevance NN which has been used in the expansion step for obtaining the top template(sorted).

**Comment by connorcoley** [comment]
Your last observation is correct, we have only one policy for expansion
rather than separate rollout and expansion policies

**Comment by tingweidaniel** [comment]
So in other words, MCTS applied in **/makeit/retrosynthetic/mcts/tree_builder.py** does not have the rollout step.  Generally, can I simply think that it just takes the following action at retrosynthesis for building up the tree?

selection (root to leaf) -> expansion -> estimate the node (price, probability, ...) -> update -> reset and repeat the previous four step until the node is solved

**Comment by connorcoley** [comment]
Yes, that’s a reasonable summary of the main steps!

**Comment by tingweidaniel** [comment]
One more thing I want to confirm.  Is the template relevance NN applied in ASKCOS the same as the [model ](https://github.com/connorcoley/retrotemp) developed by [Segler and Waller work](https://chemistry-europe.onlinelibrary.wiley.com/doi/full/10.1002/chem.201605499)?

Thank you.

**Comment by connorcoley** [comment]
Yes, that's the model we're using. The architecture isn't identical to
Marwin's, but the formulation (fingerprint rep + feed forward layers +
softmax) is the same

**Comment by tingweidaniel** [comment]
I got it.  Thank you so much.
