### ISSUE TITLE
ImportError: No module named urls

### ISSUE THREAD

**Issue by H0r53** [connorcoley/ASKCOS#30]
Greetings,
I am attempting to get a basic build of this project going. I followed the installation steps but on `docker-compose up` I'm receiving the following (shortened for brevity):

```
cr_network_worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 108, in import_default_modules
cr_network_worker_1    |     raise response
cr_network_worker_1    | ImportError: No module named urls
```

The same error occurs for multiple containers, including cr_network_worker_1, te_coordinator_1, sc_coordinator_1, tb_c_worker_1, cr_coordinator_1, tb_coordinator_mcts_1, and others.

It looks like python2 is used by the project so there is likely some dependency issue. My host is a MacOS but I'm doing everything in docker so that shouldn't be an issue.

**Comment by H0r53** [comment]
Digging deeper into the issue it appears that urls.py is a module within the askcos_site directory, and some Python path issue may be causing the module not to be recognized.

**Comment by thomasstruble** [comment]
Just to check before trying any further debugging, what specs do you have on your Mac? The full askcos stack takes >40GB of RAM to start up. If you do have that available on your machine, then another thing to check is the docker desktop for mac settings. The default MacOS allows a single container (I think) is ~4GB so when it hits this, all kinds of problems arise. You can check that under preferences -> resources.

**Comment by H0r53** [comment]
Thanks for the feedback. Although it seems unrelated to the Python module issues, you are correct that my Mac is limited in resources. I'll bump it up to see if that changes any behavior. I'm also going to try running on gcloud to further rule out any potential environment issues.

**Comment by H0r53** [comment]
I ran the setup scripts verbatim in an Ubuntu gcloud instance with more than enough resources (16 vCPUS, 60GB memory, 100GB disk) and I'm still receiving the same errors: `ImportError: No module named urls`. Something is wrong in the way that either wsgi or the Python module paths are setup.

**Comment by connorcoley** [comment]
Thanks for your patience @H0r53; it took me a couple days to get to this. That import error is not uncommon when using incorrect versions of Django (Django versions ≥2 changed project organization compared to <1). With that as a clue, I've managed to trace down the error: our `requirements.txt` file didn't pin us to a specific version of `django-extensions`, even though it did specify the now-outdated version of `Django==1.8`. I've updated the requirements to specify `django-extensions==2.2.2`, which was released around the time this codebase was originally open sourced. 

I've tested the deployment on a fresh GCP instance. If you pull to update your local version and simply re-run the build and deploy commands, you should be good to go:

```
# (6) Build & run
cd deploy
docker build -t askcos .. # build
docker-compose up -d      # start containers (detached)
docker-compose logs -f    # start tailing logs (can CTRL+C to exit)
```

edit: [link to compatibility table](https://www.djangoproject.com/download/#supported-versions) for posterity

**Comment by thomasstruble** [comment]
Would it be worth pinning all of the dependencies?

**Comment by H0r53** [comment]
Success! The latest build works. Thank you for your help with this issue.
