### ISSUE TITLE
connecting to Reaxys backend

### ISSUE THREAD

**Issue by atharvapurdue** [connorcoley/ASKCOS#33]
For the One-Step Retrosyntehsis module, if I click on the recommended reactants image, it takes me to the template page and tells that the reaxys backend is not configured.
Is there a way to configure this backend?

**Comment by thomasstruble** [comment]
It is only possible if you have a reaxys license and have an additional agreement with them to have access to their data. However, if you have access to the reaxys website you can copy/paste the reaction IDs to find the literature.

**Comment by atharvapurdue** [comment]
I have reaxys licence. 
Could you please give some details on the 'additional agreement'?
Also after that, will they provide with a api of somekind which i can use to add to the code?

**Comment by connorcoley** [comment]
The additional agreement Thomas mentioned isn't an existing well-defined agreement; you would need to separately discuss this with Elsevier. It isn't a simple plug-and-play solution and would take a small amount of code development to do any integration. The best solution as mentioned is to copy the reaction IDs into the Reaxys query builder; multiple IDs can be searched simultaneously if you concatenate them with semicolons.
