### ISSUE TITLE
Docker IP not reflecting on Browser

### ISSUE THREAD

**Issue by atharvapurdue** [connorcoley/ASKCOS#39]
![image](https://user-images.githubusercontent.com/31735343/101480418-ad860680-3979-11eb-8af0-7f6c524c9f48.png)
The following containers are activate. 
i can ping the docker container ip via ping "ip" but that ip is not visible on the browser?
Do i need to change the HOSTNAME in .env file?
Also which container is the entry point? 
is it  rabbitmq?

**Comment by mliu49** [comment]
Hi @sparklytopaz, there should be an additional nginx container which is the entrypoint. If the nginx container is running, then ASKCOS would be available at https://localhost. While the nginx container should have started automatically, you can try starting it again with `docker-compose up -d nginx`.

If you would like further help debugging the issue, could you answer the following questions?
1. What version of askcos do you have downloaded? (e.g. output of `git describe`)
2. What platform are you deploying on? (OS, local computer or cloud service)
3. Were any error messages printed during the deployment process?

**Comment by atharvapurdue** [comment]
@mliu49 
Thank you for your reply.
The issue was that tcp host port 80 was already in use and hence nginx did not start by default.
I edited the docker-compose.yml file to forward it to port 81.
i would recommened having this feature on source file itself
