### ISSUE TITLE
Dockerfile for askcos-base

### ISSUE THREAD

**Issue by Amar1729** [connorcoley/ASKCOS#44]
The Dockerfile for ASKCOS v0.4.1 (https://github.com/ASKCOS/ASKCOS/blob/v0.4.1/Dockerfile) uses `FROM askcos/askcos-base:2019.03.4-gh2855-py35`. Is the Dockerfile for that image available anywhere? The [dockerhub page](https://hub.docker.com/r/askcos/askcos-base) doesn't list it.

I would like to reference it for building ASKCOS inside a network that requires the use of RHEL (rather than debian).

**Comment by Amar1729** [comment]
Ah, I'm sorry - I missed that it was on separate branches of the `askcos-base` repository here https://github.com/ASKCOS/askcos-base/blob/2019.03.4-gh2855-py35/Dockerfile

**Comment by mliu49** [comment]
Hi @Amar1729, thanks for posting this issue! Actually, I just pushed the branch after seeing this issue. Apologies for not having it up previously.
