### ISSUE TITLE
what is ASKCOS short for??

### ISSUE THREAD

**Issue by beef-broccoli** [connorcoley/ASKCOS#47]
Sorry, non technical question lol. Just curious, since I don't see it anywhere

**Comment by connorcoley** [comment]
I think that very few of the ASKCOS contributors could define it themselves! It's sort of a pseudo-acronym at this point, but it stands for "Automated System for Knowledge-based Continuous Organic Synthesis"; this was the original title of our DARPA-funded research program encompassing both synthesis planning and automated flow chemistry.

**Comment by beef-broccoli** [comment]
ah interesting. Thanks Connor!
