### ISSUE TITLE
A question regarding your choice of reaction predictor for ImpurityPredictor class

### ISSUE THREAD

**Issue by AslantheAslan** [connorcoley/ASKCOS#49]
I have been reading the code to understand how you implemented impurity prediction. While thinking about the predictor method, I realized that WLN has been used to generate products for the given reactants. Contrary to the other modules such as forward reaction prediction and retrosynthesis, there is no option for the model in impurity prediction module in ASKCOS website. Is there any particular reason why you applied WLN but did not provide additional forward predictors such as graph2smiles? 

Also, regardless from the aforementioned topic but, why did you decide to assign a certain threshold of 30 percent for substructure match in ImpurityPrediction.check_mode_outcome? I know that finding substructures is not trivial, but I just wondered if there are some preliminary results that led you apply the function in this way.

Thanks for making your amazing application available and making it open-source.

**Comment by connorcoley** [comment]
There's no particular reason why you couldn't use other forward predictors for the impurity prediction workflow; at the time, that was the only model we had deployed for forward prediction.

That threshold is a heuristic and not a magic number. In general, I'd say that the impurity prediction pipeline is a rather crude set of heuristics/filters applied as a wrapper to the forward prediction model, and not something that was tuned to a great degree. Some folks here have been working on a more rigorous evaluation of impurity prediction, but that's unfortunately not ready to share yet!

**Comment by AslantheAslan** [comment]
I see that why it was reasonable to use WLN at that time in ASKCOS, thanks for the clarification. Adding to my previous questions, I also wonder why FastFilterScorer.evaluate_reaction_score has been employed, since reaction prediction probabilities from WLN can already be used for the same purpose. FastFilterScorer loads a model, given in askcos-data, and passes vectorized MorganFingerPrints of the outcome and the difference of outcome and input fingerprints, and this model do regression to create the insp_score for the reaction, as far as I could understand.

Lastly, I am trying to compare my model predictions with the templates given in forward.templates.json, an to do that, I use template_extractor.py which works without any problem. However, I am unable to match any of the templates given in the file. Even when I try to match the ground-truth reactions given in USPTO-480k, there is no single reaction that its template matches one of the templates given in forward.templates.json. Is there any chance that you may know why it happens? Instead of comparing canonical SMILES strings of templates, should I create fingerprints and compare them based on a threshold to see if two templates are matching?

**Comment by connorcoley** [comment]
The fast filter is a ca. 2017 model that operates much more quickly than a product prediction model does, but we have not revisited this in some time.

Are you mixing up retrosynthetic and forward synthetic templates by chance? The forward.templates.json file describes a template-based forward prediction model that the WLN model supplanted (https://pubs.acs.org/doi/10.1021/acscentsci.7b00064)

**Comment by AslantheAslan** [comment]
About fast filter, I think it is sort of redundant because WLN already provides probs that can be used as insp_score. But I understand that insp_score that comes from fast filter converges to the probability of the reaction outcome from WLN. I guess it was just optional to use fast filter. Would using the probabilities from WLN as insp_score do the same as fast filter?

About forward.templates.json, I thought the file contains unique reaction templates (17089 unique templates) from Reaxys, and the count information is how many times that particular transformation was observed in the dataset. That's why I wanted to use forward.templates.json to explain the predictions I have. My aim was to check the reaction templates of my predictions and compare with the ones in forward.templates.json. This way, I am hoping to see if the predictions of my model has templates that were seen in the Reaxys templates before.

This is all for making an explainability analysis, actually. I want to see how many of the transformations are unique or not, depending on those templates given.

Thanks for all the explanation again. Wish you a merry Christmas!

**Comment by connorcoley** [comment]
You could choose to use the WLN or other forward models as an indicator of score in the same way that the fast filter is used, sure.

For the forward templates, that is what it should contain yes. You would have to extract your templates in the exact same way if you wanted to do a string comparison to check for equality. I would instead suggest--if it is not prohibitively expensive--to simply apply one set of templates to the reactants and see if the expected/correct product is recovered

**Comment by AslantheAslan** [comment]
Thanks a lot for the detailed explanation, I think I have a better understanding about it now. I am applying both methods to see if template matches the predicted reaction. Applying templates to reactants is actually too expensive, but more useful to ensure that I am not missing any template that can actually match with the predicted reaction. I am closing the issue since I have no further question.
