### ISSUE TITLE
V1 Context recommendation with ambiguous SMILES string: O=C([O-])[O-].[Na+]

### ISSUE THREAD

**Issue by JoeDavies-6** [connorcoley/ASKCOS#50]
I wondered if there was any guidance as to how this compound should be interpreted? I have also observed this with other counterions in place of sodium. It looks somewhere between sodium bicarbonate and sodium carbonate.

**Comment by connorcoley** [comment]
From the v1 context recommender, these SMILES would have come directly from parsing MOL files from Reaxys, so I'm afraid I don't have a good answer. I would expect that it is more likely to correspond to a mis-entered sodium carbonate than sodium bicarbonate.

**Comment by JoeDavies-6** [comment]
Thanks!
